### ISSUE TITLE
Co ten obrazek, funguje?

### ISSUE THREAD

**Issue by gitpajo** [gitpajo/nfwjob#1]

**Comment by myjavarama4** [comment]
ne.

Vypisuje to tohle

Url imageimg.asp?stiid=212487

**Comment by myjavarama4** [comment]
ne.

Vypisuje to tohle

Url imageimg.asp?stiid=212487

A kam mám dát tohle

if ($pob2 == 'img_skladem') {
$pob2 = 1;
} else {
$pob2 = 0;
}

---------- Původní zpráva ----------
Od: Pavel Jorda notifications@github.com
Komu: gitpajo/nfwjob nfwjob@noreply.github.com
Datum: 16. 7. 2015 11:16:33
Předmět: [nfwjob] Co ten obrazek, funguje? (#1)

"

—
Reply to this email directly or view it on GitHub
(https://github.com/gitpajo/nfwjob/issues/1). 

"=

**Comment by gitpajo** [comment]
To je spravne, podivej se do kodu
echo "Url image".$obsah_stranky->find('div.sti_image',0)->find('img',0)->src;
staci pridat 'http://dealer.tsbohemia.cz/' a vlozit do $produkt

**Comment by gitpajo** [comment]
if ($pob2 == 'img_skladem') {
$pob2 = 1;
} else {
$pob2 = 0;
}

to uz jsem tam pridal #48abd1, ty se na ty commity nedivas?

**Comment by myjavarama4** [comment]
A proč mně to žádné comity nehlásí

---------- Původní zpráva ----------
Od: Pavel Jorda notifications@github.com
Komu: gitpajo/nfwjob nfwjob@noreply.github.com
Datum: 16. 7. 2015 11:30:21
Předmět: Re: [nfwjob] Co ten obrazek, funguje? (#1)

"

if ($pob2 == 'img_skladem') {
$pob2 = 1;
} else {
$pob2 = 0;
}

to uz jsem tam pridal, ty se na ty commity nedivas?

—
Reply to this email directly or view it on GitHub
(https://github.com/gitpajo/nfwjob/issues/1#issuecomment-121899188). 

"=

**Comment by myjavarama4** [comment]
Ten obrázek pořád nefunguje.

A co ty špatně nahrazené texty?

**Comment by gitpajo** [comment]
Jake texty?

**Comment by myjavarama4** [comment]
if ($element->find('th', 0)) {
                $prvek1 = $element->find('th', 0)->plaintext;
                $prvek1 = str_replace('Výrobce', 'vyrobce', $prvek1);
                $prvek1 = str_replace('Kód', 'kod', $prvek1);
                $prvek1 = str_replace('Part No.', 'part_no', $prvek1);
                $prvek1 = str_replace('Dostupnost na eshopu', 'dostupnost_eshop', $prvek1);
                $prvek1 = str_replace('Objednat', '', $prvek1);
                $prvek1 = str_replace('Vaše cena bez DPH', 'cena_bez_dph', $prvek1);
                $prvek1 = str_replace('Recyklační poplatek (RP_)', 'recyklacni_poplatek', $prvek1);
                $prvek1 = str_replace('Autorský fond (AF_)', 'autorsky_fond', $prvek1);
                $prvek1 = str_replace('Vaše cena s RP_\+ AF_', 'cena_s_rp_af', $prvek1);
                $prvek1 = str_replace('Vaše cena s DPH', 'cena_s_rp_af', $prvek1);
                $prvek1 = str_replace('Garance ceny', '', $prvek1);
                $prvek1 = str_replace('Záruka spotřebitel', 'zaruka_spotrebitel', $prvek1);
                $prvek1 = str_replace('Záruka ostatní', 'zaruka_ostatni', $prvek1);
                $prvek1 = str_replace('Status', 'status', $prvek1);
                $prvek1 = str_replace('dostupnos_pobocky', 'dostupnost_pobocky', $prvek1);
            }
Něco se nahradí, něco ne
