### ISSUE TITLE
Odstranit prázdné závorky

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#10]
[parametry] => Array
        (
            [Formát disku [palců]:] => 2,5
            [Hloubka [mm]:] => 100
            [Hmotnost [g]:] => 78,6
            [Max. rychlost čtení [MB/s]:] => 545
            [Max. rychlost zápisu [MB/s]:] => 430
            [Podpora OS:] => Windows Vista
            [Provedení:] => interní
            [Rozhraní:] => SATA III
            [Šířka [mm]:] => 69,85
            [Technologie TRIM                  :] => ano
            [Technologie výroby [nm]:] => 16
            [Typ disku:] => SSD
            [Typ NAND paměti               :] => MLC
            [Velikost disku [GB]:] => 120
            [Výška [mm]:] => 7
            [ ] =>

**Comment by gitpajo** [comment]
table s class=sti_details je tam vickrat, nejdriv vyhledam div s parametry a pak teprve prochazim tabulku
$div = $obsah_stranky->find('div[id=parametry]', 0);
foreach ($div->find('table[class=sti_details]') as $tabulka) {
