### ISSUE TITLE
Trim popis

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#13]
Nefunguje

$produkt['popis'] = trim($popis);

**Comment by gitpajo** [comment]
jeste pred trim
        $popis = str_replace(html_entity_decode('&nbsp;'), ' ', $popis);

**Comment by myjavarama4** [comment]
private static function getPopis($obsah_stranky, $produkt) {
        $popis = $obsah_stranky->find('div[id=popis-produktu]', 0)->plaintext;
        $popis = str_replace(html_entity_decode(' '), ' ', $popis);
        $produkt['popis'] = trim($popis);
        return $produkt;
    }

Nefunguje
