### ISSUE TITLE
zapomneli jsme na nazev produktu, dejme ho do klice [nazev]

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#15]

**Comment by gitpajo** [comment]
musis zjistit kde je nazev, udelat find a pridat do $produkt['nazev']

**Comment by myjavarama4** [comment]
Nějak jsem to ale nepochopil

**Comment by gitpajo** [comment]
ja takhle, co jsi nasel ty? 
find('div[class=f_left product_name]', 0)

**Comment by gitpajo** [comment]
Tak co funguje?

**Comment by myjavarama4** [comment]
wait
