### ISSUE TITLE
Jak mám udělat to unset do funkce

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#16]

**Comment by gitpajo** [comment]
Prvni udelej to #15

**Comment by gitpajo** [comment]
ja takhle, co jsi nasel ty? 
find('div[class=f_left product_name]')

**Comment by myjavarama4** [comment]
private static function unsetInformation($produkt) {
        foreach ($produkt as $klic => $value) {
            if ($klic == 'Dostupnost na pobočkách') {
                unset($produkt[$klic]);
            }
            if ($klic == 'Hodnocení produktu') {
                unset($produkt[$klic]);
            }
            if ($klic == 'Garance ceny') {
                unset($produkt[$klic]);
            }
            if ($klic == 'Mám o tento produkt zájem:') {
                unset($produkt['parametry'][$klic]);
            }
        }
        return $produkt;
    }

Poslední funguje, zbytek ne

**Comment by gitpajo** [comment]
Musis tu funkci volat az jsou ty informace nactene, nejlepe na konci getProdukt
Nejde odstranit to co tam jeste neni

**Comment by myjavarama4** [comment]
self::unsetInformation($produkt);

Přesunul jsem na konec a nemá vliv

**Comment by myjavarama4** [comment]
už jsi na to došel?

**Comment by gitpajo** [comment]
commitni to at to vidim

**Comment by myjavarama4** [comment]
Pořád to nefunguje, i když jsem to přesunul, poslední commit

**Comment by gitpajo** [comment]
Uloz návratovou hodnotu do $produkt
