### ISSUE TITLE
EraseInformation

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#19]
private static function eraseSpace($promenna) {
        $promenna = str_replace(html_entity_decode('&nbsp;'), ' ', $promenna);
        $promenna = trim($promenna);
        return $promenna;
    }

PHP Warning: trim() expects parameter 1 to be string, array given in

Zprav to, já už na to nemám nervy

**Comment by gitpajo** [comment]
Odebral jsi paramatr $produkt v deklaraci, ale nechal jsi ho ve volani

**Comment by myjavarama4** [comment]
Kdo má taky na to všechno myslet

**Comment by gitpajo** [comment]
Jo je to drina. Budes si tech penez vazit
