### ISSUE TITLE
Nahrazování textů

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#2]
Proč se některé texty nahrazují a některé ne?

$prvek1 = str_replace('Vaše cena s RP_\+ AF_', 'cena_s_rp_af', $prvek1);

Toto nedělá absolutně nic, ale proč, když tam ten text je?

**Comment by myjavarama4** [comment]
```
            $prvek1 = str_replace('Recyklační poplatek (RP*)', 'recyklacni_poplatek', $prvek1);
            $prvek1 = str_replace('Autorský fond (AF*)', 'autorsky_fond', $prvek1);
```

Tohle pořád nefunguje

**Comment by gitpajo** [comment]
Jsou tam 2 mezery před závorkou
'Recyklační poplatek (RP_)'
'Recyklační poplatek  (RP_)'
