### ISSUE TITLE
Nemažou se mezery v parametrech

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#20]

**Comment by gitpajo** [comment]
Jeste  
$hodnota = self::eraseSpace($hodnota);
co rikas?

**Comment by myjavarama4** [comment]
Pořád nic

**Comment by gitpajo** [comment]
Pridals ?
$hodnota = self::eraseSpace($hodnota);

**Comment by myjavarama4** [comment]
ano přidal

private static function getParametr($obsah_stranky, $produkt) {
        $div = $obsah_stranky->find('div[id=parametry]', 0);
        foreach ($div->find('table[class=sti_details]') as $tabulka) {
            $podminka = false;
            foreach ($tabulka->find('tr') as $parametry) {
                if ($podminka == true) {
                    $klic = '';
                    $hodnota = '';
                    if ($tabulka->find('td', 0)) {
                        $klic = $parametry->find('td', 0)->plaintext;
                        $klic = self::eraseSpace($klic);
                    }
                    if ($tabulka->find('td', 1)) {
                        $hodnota = $parametry->find('td', 1)->plaintext;
                        $hodnota = self::eraseSpace($hodnota);
                    }
                    if ($klic && $hodnota) {
                        $produkt['parametry'][$klic] = $hodnota;
                    }
                }
                $podminka = true;
            }
        }
        return $produkt;
    }

**Comment by gitpajo** [comment]
Myslis tu mezeru pred dvojteckou?

**Comment by myjavarama4** [comment]
ano

**Comment by gitpajo** [comment]
To musis rict
A ted silne PHP, odstrani dvojtecku. Pridej do eraseSpace
trim($klic, ':')

**Comment by myjavarama4** [comment]
Úžasné (sarkasmus)
