### ISSUE TITLE
Smazat dvojtou šipku

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#21]
[DLE VÝROBCE] =>  -> Acer -> Počítače -> Stolní počítače ->   PC Aspire
        )

**Comment by gitpajo** [comment]
Tu prvni jednoduchou, ale tu dvojitou nejde. To tam dava print_r

**Comment by myjavarama4** [comment]
Tak tu první jednoduchou

**Comment by gitpajo** [comment]
Zkus
if ($produkt['zarazeni'][$kategorie] == '') {
   $produkt['zarazeni'][$kategorie] .= $zarazeni->plaintext;
} else {
 $produkt['zarazeni'][$kategorie] .= ' -> ' . $zarazeni->plaintext;
}

**Comment by myjavarama4** [comment]
Maže se to, ale vypisuje to nějak divně

```
        [DLE VÝROBCE] => DLE VÝROBCE -> 
```

 -> 
 -> Acer -> 
 -> Počítače -> 
 -> Stolní počítače -> 
 ->   PC Aspire ->

**Comment by gitpajo** [comment]
Commitni to, me to jde pekne a jake cislo produktu, to v url?

**Comment by myjavarama4** [comment]
Ale mně to nejde pěkně

**Comment by gitpajo** [comment]
Tak jeste jednou, commitni to a jake cislo produktu, to v url?
