### ISSUE TITLE
Smazat mezery v zařazení

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#22]

**Comment by myjavarama4** [comment]
Mezera se pořád nemaže

**Comment by gitpajo** [comment]
delas eraseSpace $kategorie, musis i hodnotu

**Comment by myjavarama4** [comment]
nechápu

**Comment by MichalDM** [comment]
private static function getInclusion($obsah_stranky, $produkt) {
        foreach ($obsah_stranky->find('div[id=zarazeni-produktu]') as $tabulka) {
            $podminka = TRUE;
            $i = 0;
            $j = 0;
            $zarazeni = $tabulka->find('strong.hcat', 0);
            while ($podminka && $zarazeni) {
                if ($zarazeni->next_sibling() != null) {
                    if ($zarazeni->tag == 'strong') {
                        $kategorie = $zarazeni->plaintext;
                        $kategorie = self::eraseSpace($zarazeni);
                        $produkt['zarazeni'][$kategorie] = '';
                    }
                    if ($zarazeni->tag == 'a') {
                        if ($produkt['zarazeni'][$kategorie] == '') {
                            $produkt['zarazeni'][$kategorie] .= $zarazeni->plaintext;
                        } else {
                            $produkt['zarazeni'][$kategorie] .= ' -> ' . $zarazeni->plaintext;
                        }
                    }
                    $zarazeni = $zarazeni->next_sibling();
                } else {
                    $podminka = FALSE;
                }
                $i++;
                $j++;
            }
        }
        return $produkt;
    }

**Comment by gitpajo** [comment]
radek 219 a 221 je potraba eraseSpace
