### ISSUE TITLE
Pole obrázků

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#23]
Tento produkt

http://dealer.tsbohemia.cz/?cls=stoitem&stiid=207401

obsahuje více obrázků, ovšem program načte jenom jeden

**Comment by gitpajo** [comment]
Mrknu na to

**Comment by gitpajo** [comment]
find('div[clas=sti_detail_gallery]')

**Comment by gitpajo** [comment]
$divs = $obsah_stranky->find('div[clas=sti_detail_gallery]');
foreach($divs as $div) {
   $div->find('img',0)->src;

**Comment by myjavarama4** [comment]
Místo čeho to napsat?

**Comment by gitpajo** [comment]
Do te funkce getImage. Pridat, nic nemazat. Mas to dobre to zakomentovane a tu zavorku posun nahoru

**Comment by myjavarama4** [comment]
Comit - teď se nezobrazuje vůbec nic

**Comment by myjavarama4** [comment]
Došel jsi na to?

**Comment by gitpajo** [comment]
Zkus

**Comment by myjavarama4** [comment]
Chvála bohu
