### ISSUE TITLE
Produkt nenalezen

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#27]
Uložení textu produkt nenalezen do souboru

**Comment by gitpajo** [comment]
Do pole $produkt pridas text produkt nenalezen

**Comment by myjavarama4** [comment]
Vyřešeno (bez cizí pomoci HAHA)

**Comment by myjavarama4** [comment]
Co je zase?

**Comment by myjavarama4** [comment]
Vždyť to funguje

**Comment by gitpajo** [comment]
Takhle je to hezci
$produkt = array('status' => 'Produkt nenalezen ', 'url' => $url);
self::saveProduct($produkt, $soubor);

**Comment by myjavarama4** [comment]
Opraveno

**Comment by gitpajo** [comment]
Kdyz das do commitu fix #27 nebo close #27 tak se uzavre

**Comment by gitpajo** [comment]
SHA: b99779018efe478c87cc9c10e56e5ae27c2d1781
