### ISSUE TITLE
Opravit funkci isProduct

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#29]
Jeslti nenalezne url, vyhodí produkt nenalezen

**Comment by gitpajo** [comment]
Mrknu na to, ale to staci az bude fungovat ostatni

**Comment by myjavarama4** [comment]
v pohodě, stačí do 11:00

**Comment by gitpajo** [comment]
$div = $obsah_stranky->find('div[itemtype=http://schema.org/Product]',0);
if ($div) {
  return true;
} else {
  return false;
}

**Comment by myjavarama4** [comment]
nefunguje to
