### ISSUE TITLE
Zařazení

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#3]
v klici zarazeni mame:
[DLE VÝROBCE] => Array
                (
                    [0] => Tiskárny 
                    [1] => Multifunkční
                    [2] => OKI
                    [3] => Multifunkční tiskárny
                )
spravne by to melo byt takto:
[DLE VÝROBCE] => Array
                (
                    [0] => Tiskárny -> Multifunkční
                    [1] => OKI -> Multifunkční tiskárny
                )

Ty jsi psal tu funkci, navíc chci to udělat než půjdu

**Comment by gitpajo** [comment]
Jaké je url toho produktu?

**Comment by myjavarama4** [comment]
Cože?

**Comment by gitpajo** [comment]
Už to vim

**Comment by gitpajo** [comment]
Lepsi bude pouzit children

**Comment by myjavarama4** [comment]
Call to a member function next_sibling() on null

Řádek 176

**Comment by gitpajo** [comment]
Mas na radku 176 neco jineho nez na githubu

**Comment by myjavarama4** [comment]
$produkt['zarazeni'][$kategorie] .= ' -> ' . $eee->plaintext;

Tenhle řádek

**Comment by myjavarama4** [comment]
V tomhle řádek je problém

 if ($eee->next_sibling() != null)

**Comment by myjavarama4** [comment]
Pořád to vypisuje stejnou chybu

**Comment by gitpajo** [comment]
ale tady zadny next_sibling neni

**Comment by myjavarama4** [comment]
function getInclusion($obsah_stranky, $produkt) {
    foreach ($obsah_stranky->find('div[id=zarazeni-produktu]') as $tabulka) {
        $podm = TRUE;
        $i = 0;
        $j = 0;
        $eee = $tabulka->find('strong.hcat', 0);
        while ($podm && $eee) {
            if ($eee->next_sibling() != null) {
                if ($eee->tag == 'strong') {
                    $kategorie = $eee->plaintext;
                }
                if ($eee->tag == 'a') {
                    $produkt['zarazeni'][$kategorie] .= ' -> ' . $eee->plaintext;
                }
                $eee = $eee->next_sibling();
            } else {
                $podm = FALSE;
            }
            $i++;
            $j++;
        }
    }
    return $produkt;
}

Teď to vypisuje chybu tady

 $produkt['zarazeni'][$kategorie] .= ' -> ' . $eee->plaintext;

12 chyb, všechny cosi undefined index
