### ISSUE TITLE
opravit funkci getInformation

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#30]
private static function getInformation($obsah_stranky, $produkt) {
        $table = $obsah_stranky->find('TABLE BORDER="0"', 1);
        $radky = $table->find('tr');
        foreach ($radky as $radek) {
            $klic = self::findFirst($radek, 'td')->plaintext;
            $hodnota = $radek->find('td', 1)->plaintext;
            $produkt['informace'][$klic] = $hodnota;
            if ($radek->next_sibling() == null) {
                break;
            }
        }
        return $produkt;
    }

Nevypisuje to nic, ale nehází to žádnou chybu

[informace] => Array
        (
            [] =>  
        )

**Comment by gitpajo** [comment]
Spravne se to pise takhle $table = $obsah_stranky->find('TABLE[BORDER=0]', 1);
ale tam maji vsechny tabulky BORDER

Takhle je to lepsi

$div = $obsah_stranky->find('div[itemtype=http://schema.org/Product]',0);
$radky = $div->find('tr');

a ten braek je zbytecny, foreach skonci, kdyz tam nebude dalsi sourozenec

**Comment by gitpajo** [comment]
Tech bunek td je tam moc, musis tam dat podminku na jednotliva pole
vyber si jedno a na nem to testuj
Treba to Price:

**Comment by myjavarama4** [comment]
http://schema.org/Product

What the hell is this

**Comment by gitpajo** [comment]
takovy je ten div 
&lt;div itemscope itemtype="http://schema.org/Product"&gt;

**Comment by myjavarama4** [comment]
I hate who write this fucking page

**Comment by gitpajo** [comment]
Pouzil jsem ten tvuj zpusob na hledani jmena, ten je pekny  

  $name_td = $obsah_stranky->find('span[itemprop=name]', 0);
  echo $name_td->plaintext;
  $dalsi = $name_td->parent()->parent()->parent()->parent()->next_sibling();
  echo $dalsi->find('td',1)->plaintext;
  $dalsi = $dalsi->next_sibling();
  echo $dalsi->find('td',1)->plaintext;
  $dalsi = $dalsi->next_sibling();
  echo $dalsi->find('td',1)->plaintext;
  $dalsi = $dalsi->next_sibling();
  echo $dalsi->find('td',1)->plaintext;

**Comment by myjavarama4** [comment]
Momentálně to vypisuje tohle

Array
(
    [nazev] => 
    [stopy] => 1. Immigrant Song 
2. Friends 
3. Celebration Day 
4. Since I've Been Loving You 
5. Out On The Tiles 
6. Gallows Pole
7. Tangerine
8. That's The Way
9. Bron Y Aur Stomp
10. Hats Off To (Roy) Harper
    [dostupnost] => In Stock - Buy before 2:30pm for First Class Postage today
    [rok] => 1970 - 45 years old
    [umelec] => Led Zeppelin (click here for complete listing)
    [dilo] => 
    [cena] => £ 50.00                                change currency
    [format] => vinyl LP album (LP record)
    [vydavatel] => Atlantic
    [zeme_puvodu] => USA  
    [souvisejici_umelci] => Band Of Joy, Bonham, Broken Glass, Carter-Lewis & The Southerners, Cartoone, Coverdale Page, Deborah Bonham, Dread Zeppelin, Far Corporation, Jimmy Page, John Paul Jones, Lez Zeppelin, Listen (60s), Lord Sutch, Page & Plant, Pattty Griffin, Paul, Robert Plant, The Honeydrippers, The Outsiders (UK), Them Crooked Vultures
)

Skladby by se měli vypisovat vedle sebe, stejně jako umelci
name se nevypisuje, hlásí chybu PHP Notice: Trying to get property of non-object in ...\nfw\app\front\templates\home\ProductInfoEil.php:54

dilo se nevypisuje, nehlásí chybu

**Comment by gitpajo** [comment]
Mrknu na to

**Comment by gitpajo** [comment]
To name musis dat find_first

**Comment by myjavarama4** [comment]
kam mám napsat to replace?

**Comment by gitpajo** [comment]
No pred tim nez to vlozis do $produkt

**Comment by myjavarama4** [comment]
if ($bunka->plaintext == 'Tracklisting / Additional Info:') {
                        $promenna = self::eraseSpace($bunka->next_sibling()->plaintext);
                        $promenna = str_replace('br', '', $promenna);
                        $produkt['stopy'] = $promenna;

Tvoje odpovědi fakt zbožňuju

**Comment by gitpajo** [comment]
Umisteni dobre, ale zjistil jsem, ze to nedela br, ale konec radku

$promenna = str_replace("\r\n", '', $promenna);

a chce to peknejsi nazev promene

**Comment by myjavarama4** [comment]
tak vymysli, mě žádný nenapadá

**Comment by gitpajo** [comment]
$track_list
