### ISSUE TITLE
Related Artists

### ISSUE THREAD

**Issue by gitpajo** [gitpajo/nfwjob#31]
Udelej samostatnou funkci
Predas ji $bunka a $produkt

```
      $artists = $bunka->next_sibling()->find('a');
      foreach ($artists as $artist) {
        $produkt['souvisejici_umelci'][] = $artist->plaintext;
      }
```

**Comment by myjavarama4** [comment]
private static function getArtist($bunka, $produkt) {
        $artists = $bunka->next_sibling()->find('a');
        foreach ($artists as $artist) {
            $produkt['souvisejici_umelci'][] = $artist->plaintext;
        }
    }

else if ($bunka->plaintext == 'Related Artists:') {
                        self::getArtist($bunka, $produkt);
                    }

nic to nevypisuje

**Comment by gitpajo** [comment]
return

**Comment by myjavarama4** [comment]
private static function getArtist($bunka, $produkt) {
        $artists = $bunka->next_sibling()->find('a');
        foreach ($artists as $artist) {
            $produkt['souvisejici_umelci'][] = $artist->plaintext;
        }
        return $produkt;
    }

else if ($bunka->plaintext == 'Related Artists:') {
self::getArtist($bunka, $produkt);
}

Stejný výsledek

**Comment by gitpajo** [comment]
no tu navratovou hodnotu musi pouzit

podivej se trba na to jak pouzivas getName

číst číst číst
