### ISSUE TITLE
produkt.txt

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#32]
Podívej se na ten soubor, vypisuje se tam nbsp a nějaké change curency, které tam nemá být

**Comment by gitpajo** [comment]
&amp;nbsp; odstranis pomoci str_replace

&amp;pound; je v html symbol libry 

a change curency musis taky replacenout

**Comment by myjavarama4** [comment]
zase, kam to mám napsat, a taky nebylo by lepší trim

**Comment by gitpajo** [comment]
&amp;nbsp; do eraseSpace, trim je vhodne na jeden znak

change curency primo do podminky na Price

**Comment by myjavarama4** [comment]
to change curency nefunguje pořád

$cena = self::eraseSpace($bunka->next_sibling()->plaintext);
$cena = str_replace('change curency', '', $cena);
$produkt['cena'] = $cena;

**Comment by gitpajo** [comment]
currency má dvě r
a dej to pred to eraseSpace

**Comment by myjavarama4** [comment]
tyto gramatické překlepy mě už lezou na kočku

**Comment by gitpajo** [comment]
Dnes ti to jde pěkně
