### ISSUE TITLE
jeste prosim pridat jeden klic [obrazky] a tam bude pole fotografii (url)

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#33]
Úžasné, to by mě zajímalo, jaké obrázky měl na mysli

**Comment by gitpajo** [comment]
Jsou tam dva obrazky, obal a cd
Jdu to zkusit napsat find, udelej funkci getImage

**Comment by gitpajo** [comment]
Prvni obrazek $obsah_stranky->find('img[itemprop=image]', 0)->src

**Comment by gitpajo** [comment]
Dalsi obrazky jsou next_sibling()

$img = $obsah_stranky->find('img[itemprop=image]', 0);
$img = $img->next_sibling();
if ($img) {
    echo $img->src;
}

**Comment by myjavarama4** [comment]
private static function getImage($obsah_stranky, $produkt) {
        $obsah_stranky->find('img[itemprop=image]', 0)->src;
        $img = $obsah_stranky->find('img[itemprop=image]', 0);
        $img = $img->next_sibling();
        if ($img) {
            echo $img->src;
        }
        return $produkt;
    }

Nechápu, musíš mi to vysvětlit, nechce se mi to zkoumat.

**Comment by gitpajo** [comment]
commitl jsem to
je to jen pro dva obrazky
pro vice musis udelat cyklus

**Comment by myjavarama4** [comment]
Co je zase špatně

 $img = self::findFirst($obsah_stranky, 'img[itemprop=image]');
        $produkt['img'][] = $img->src;
        $podminka = true;
        while ($podminka) {
            if ($img->next_sibling() != NULL) {
                $produkt['img'][] = $img->src;
            } else {
                $podminka = false;
            }
        }
        return $produkt;

Pravděpodobně nekonečný cyklus, ale proč?

**Comment by gitpajo** [comment]
Nemam zadny produkt s vice jak 2 obrázkama

**Comment by myjavarama4** [comment]
To je jedno, cyklus je lepší, ale co je tam špatně?

**Comment by gitpajo** [comment]
promenou $img mas porad stejnou

```
while ($podminka) {
  if ($img->next_sibling() != NULL) {
    $img = $img->next_sibling();
    $produkt['img'][] = $img->src;
  } else {
    $podminka = false;
  }
}
```

**Comment by gitpajo** [comment]
Podivej jak jsem hezky odsadil ten predchozi comment
