### ISSUE TITLE
Špatné url

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#35]
[0] => /images/main/Led-Zeppelin-Led-Zeppelin-III-587277.jpg
[1] => /Gallery/587277b.jpg

Proč se vypisuje tohle a ne url?

**Comment by gitpajo** [comment]
pridej tam to self::SERVER_URL

**Comment by myjavarama4** [comment]
private static function getImage($obsah_stranky, $produkt) {
        $img = self::findFirst($obsah_stranky, 'img[itemprop=image]');
        $produkt['img'][] = self::SERVER_URL . $img->src;
        $podminka = TRUE;
        while ($podminka) {
            if ($img->next_sibling() != NULL) {
                $img = $img->next_sibling();
                $produkt['img'][] = self::SERVER_URL . $img->src;
            } else {
                $podminka = FALSE;
            }
        }
        return $produkt;
    }

Prohlížeči to nevadí, ale jak tam dostanu jenom jedno lomítko

http://eil.com//images/main/Led-Zeppelin-Led-Zeppelin-III-587277.jpg

**Comment by gitpajo** [comment]
trim($img->src, '/')
:+1:
