### ISSUE TITLE
Nový úkol

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#36]
http://www.ice.com/earrings/diamond-earrings/gemstone-earring-prd-ecc-105466/ [^]

vysledek ma vypadat takto:
array (
  'nazev' => '4 3/8 Carat Amethyst & White Topaz Sterling Silver Ring',
  'cena_bezna' => '$65.00',
  'cena' => '$65.00',
  'popis' => 'This luxury ring looks stunning paired with a simple cocktail dress. A rich round cut amethyst is surrounded by crystal clear white topaz all totaling 4 3/8 carats in polished sterling silver.',
  'parametry' => 
  array (
    0 => 
    array (
      'Ring___1' => 'Sterling Silver',
      'uprava___2' => 'Polished',
      'sirka___3' => '5/8 inch',
      'vaha___4' => '5.8 gram (approx. weight',
    ),
    1 => 
    array (
      'Amethyst:___1' => '_',
      'barva___2' => 'Purple',
      'Number of Stones___3' => '1',
      'tvar___4' => 'Round',
      'vaha___5' => '3 carat TGW',
    ),
    2 => 
    array (
      'Topaz:___1' => '_',
      'barva___2' => 'White',
      'Number of Stones___3' => '16',
      'tvar___4' => 'Round',
      'vaha___5' => '1.44 carat TGW',
    ),
  ),
  'vyprodano' => 0,
  'iceid' => 'RSY_102401',
  'dalsi_obrazky' => 
  array (
  ),
  'obrazek' => 'http://assets.ice.com/media/catalog/product/cache/2/image/1440x800/9df78eab33525d08d6e5fb8d27136e95/r/s/rsy_102401_b-4_38_carat_amethyst__white_topaz_sterling_silver_ring.jpg', [^]

**Comment by myjavarama4** [comment]
Kdyžtak to uděláme o výkendu, teď už na to kašlu.

**Comment by gitpajo** [comment]
To vypada na pekne udelaný web, class
:dog2:

**Comment by myjavarama4** [comment]
odkaz odkazuje na existující výrobek, ale výpis k tomu je jiný výrobek, tam uděláme ten z odkazu

**Comment by myjavarama4** [comment]
zatím to tak nechám, kdyžtak se to potom upraví
