### ISSUE TITLE
Abstraktní třída getProduct

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#37]

**Comment by gitpajo** [comment]
Commit ada7ba9718339b9c640730d1a1966a20d4bf2620 :rabbit:

**Comment by myjavarama4** [comment]
Úžasné

Static function ProductInfo::getProduct() should not be abstract

**Comment by myjavarama4** [comment]
UU

**Comment by gitpajo** [comment]
zatim tam tu funkci nedavej, udelame to pomoci interface

**Comment by gitpajo** [comment]
Na obede ti to reknu
