### ISSUE TITLE
Img next sibling

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#39]
[nazev] => Led Zeppelin Led Zeppelin III - VG US  vinyl LP album (LP record)
    [stopy] => 1. Immigrant Song 2. Friends 3. Celebration Day 4. Since I've Been Loving You 5. Out On The Tiles 6. Gallows Pole7. Tangerine8. That's The Way9. Bron Y Aur Stomp10. Hats Off To (Roy) Harper
    [dostupnost] => In Stock - Buy before 2:30pm for First Class Postage today
    [rok] => 1970 - 45 years old
    [umelec] => Led Zeppelin (click here for complete listing)
    [dilo] => Led Zeppelin III - VG(click here for more of the same title)
    [cena] => £ 50.00
    [format] => vinyl LP album (LP record)
    [vydavatel] => Atlantic
    [zeme_puvodu] => USA
    [souvisejici_umelci] => array(Band Of Joy, Bonham, Broken Glass, Carter-Lewis & The Southerners, Cartoone, Coverdale Page, Deborah Bonham, Dread Zeppelin, Far Corporation, Jimmy Page, John Paul Jones, Lez Zeppelin, Listen (60s), Lord Sutch, Page & Plant, Pattty Griffin, Paul, Robert Plant, The Honeydrippers, The Outsiders (UK), Them Crooked Vultures)
    [img] => Array
        (
            [0] => http://eil.com//images/main/Led-Zeppelin-Led-Zeppelin-III-587277.jpg
            [1] => http://eil.com//Gallery/587277b.jpg
        )

)
Fatal error: Call to a member function next_sibling() on null in C:\xampp\htdocs\nfw\app\front\templates\home\ProductInfoEil.php on line 56

**Comment by myjavarama4** [comment]
//    $name = self::findFirst($obsah_stranky, 'span[itemprop=name]')->plaintext;
     //   $produkt['nazev'] = self::eraseSpace($name);

//        $produkt['img'][] = $img->src;

/_while ($podminka) {
            if ($img->next_sibling() != NULL) {
                $img = $img->next_sibling();
                $produkt['img'][] = $img->src;
            } else {
                $podminka = FALSE;
            }
        }_/

Array
(
    [stopy] => 1. Immigrant Song 2. Friends 3. Celebration Day 4. Since I've Been Loving You 5. Out On The Tiles 6. Gallows Pole7. Tangerine8. That's The Way9. Bron Y Aur Stomp10. Hats Off To (Roy) Harper
    [dostupnost] => In Stock - Buy before 2:30pm for First Class Postage today
    [rok] => 1970 - 45 years old
    [umelec] => Led Zeppelin (click here for complete listing)
    [dilo] => Led Zeppelin III - VG(click here for more of the same title)
    [cena] => £ 50.00
    [format] => vinyl LP album (LP record)
    [vydavatel] => Atlantic
    [zeme_puvodu] => USA
    [souvisejici_umelci] => array(Band Of Joy, Bonham, Broken Glass, Carter-Lewis & The Southerners, Cartoone, Coverdale Page, Deborah Bonham, Dread Zeppelin, Far Corporation, Jimmy Page, John Paul Jones, Lez Zeppelin, Listen (60s), Lord Sutch, Page & Plant, Pattty Griffin, Paul, Robert Plant, The Honeydrippers, The Outsiders (UK), Them Crooked Vultures)
)
Array
(
)

Zakomentováno, vypisuje se, nehlásí žádnou chybu

**Comment by gitpajo** [comment]
Hledám chybu, bez pracovat na tom ice

**Comment by gitpajo** [comment]
Radek 73 soubor default.php 
Preklep a priste mi věř

**Comment by myjavarama4** [comment]
ta svině, vidíš ale, chyba byla na obou stranách, nejenom u mě

Vidíš, v javě bych takový problém nikdy neudělal, to by mně NetBeans nedovolilo.

No PHP, co bys od toho chtěl?

**Comment by gitpajo** [comment]
Prvni parametr je $url je String, to neohlida žádné NetBeans
Hlavni je nepropadat panice a :smirk_cat:

**Comment by gitpajo** [comment]
Díky za :book:
