### ISSUE TITLE
Zbytek

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#4]
parametr [Mám o tento produkt zájem:] => ano ne dame pryc

[dostupnost_eshop] => Skladem --- Skladem by kolem sebe nemelo mit mezery

url_image by melo byt pole (situace kdy ma produkt vice obrazku)

Ještě tohle.

**Comment by gitpajo** [comment]
mezery se odstranuji funkci trim

url_image - musis tam dat find bez nuly a do foreach jako treba 'tr'

**Comment by myjavarama4** [comment]
Všechno už mám, ale to url_image jsem nepochopil

**Comment by gitpajo** [comment]
na ostraneni pouzij unset ne replace
