### ISSUE TITLE
2 lomítka

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#40]
Jak je možné, že u TSBohemia se nevypisují 2 lomítka za cz, ale u eil ano

**Comment by myjavarama4** [comment]
Poslední commit

**Comment by gitpajo** [comment]
Tak je to na te strance, v src to zacina lomitkem a SRVER_URL konci lomitkem a na druhe strance to zacina images...
jednoducha pomoc replace('//', '/'
