### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#42]
ProductInfoEil::getProduct(ProductInfoTSBohemia::SERVER_URL . 'shop/moreinfo.asp?catalogid=587277', $soubor);

Hlásí chybu

PHP Warning: file_get_contents(http://dealer.tsbohemia.cz/shop/moreinfo.asp?catalogid=587277): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in ...\nfw\class\core\simpledom\simple_html_dom.php:76

Poslední commit

**Comment by myjavarama4** [comment]
Už to funguje

**Comment by myjavarama4** [comment]
Tak nic, hlásí to ŠPATNÉ URL, ale když napíšu tohle, což nedává smysl

ProductInfoEil::getProduct(ProductInfoEil::SERVER_URL . 'shop/moreinfo.asp?catalogid=587277', $soubor);

Když zadám tohle, tak to hlásí zase

PHP Warning: file_get_contents(http://dealer.tsbohemia.cz/shop/moreinfo.asp?catalogid=587277): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
in ...\nfw\class\core\simpledom\simple_html_dom.php:76

ProductInfoEil::getProduct(ProductInfoTSBohemia::SERVER_URL . 'shop/moreinfo.asp?catalogid=587277', $soubor);

**Comment by gitpajo** [comment]
musis tam mit === 3x, protoze 0 je taky false

**Comment by myjavarama4** [comment]
Pořád stejná chyba

**Comment by gitpajo** [comment]
ty 3 === jsou tam, aby fungovalo, když je to dobře

**Comment by myjavarama4** [comment]
ano, ale co když je špatné url

**Comment by gitpajo** [comment]
Tu kontrolu na domenu musime dat jeste pred to cteni te stranky a ten warning je v poradku, vysvetlim na obede
