### ISSUE TITLE
IsProduct

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#43]
Nutno dořešit u ProductInfoIce.php

**Comment by gitpajo** [comment]
Uz jsem dorazil, jdu se na to podivat

**Comment by gitpajo** [comment]
je to podobny zpusob jako to Eil

$div = self::findFirst($obsah_stranky, 'div[itemprop=name]');
if ($div) ...

**Comment by myjavarama4** [comment]
Poslední commit

**Comment by myjavarama4** [comment]
nefunkční, hlásí produkt nenalezen, přitom existuje.
