### ISSUE TITLE
Function eraseFile do class ProductInfo

### ISSUE THREAD

**Issue by gitpajo** [gitpajo/nfwjob#45]

**Comment by myjavarama4** [comment]
jak duplicate?

**Comment by gitpajo** [comment]
jako ze mas funkce  pro mazani a ukladani na dvou mistech v ProductInfo a default
default je pouye pro tebe na volani, nekdo jiny bude mit jen ty class
:pear:

**Comment by myjavarama4** [comment]
já su pes, takhle to udělat nejde, eraseFile se volá vždy při volání funkce getProduct, takže se vždycky smaže a zůstane tam poslední, proto to u jednoho produktu nevadí.

Budu to muset dat zpátky stejně jako předtím

**Comment by gitpajo** [comment]
U tech 30ti to vadi, u jednoho ne :koala:

**Comment by myjavarama4** [comment]
ano
