### ISSUE TITLE
TSBOHEMIA

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#48]
ZASE TO NEFUNGUJE,

VYPISUJE TO POUZE POSLEDNÍ PRODUKT, I KDYŽ JSEM ERASEFILE SMAZAL Z GETPRODUCT

**Comment by gitpajo** [comment]
Chybi ti tam **FILE_APPEND**

```
file_put_contents($soubor, $obsah, FILE_APPEND);
```
