### ISSUE TITLE
Led Z

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#49]
Umělec vypisuje Led Z, místo Led Zeppelin

Poslední commit

**Comment by gitpajo** [comment]
Rikals, ze to tam pise to click?

**Comment by myjavarama4** [comment]
Původně tam bylo tohle
Led Zeppelin (click here for complete listing)

Když přidám

$umelec = self::eraseSpace($bunka->next_sibling()->plaintext);
$umelec = trim($umelec, '(click here for complete listing)');
$produkt['umelec'] = $umelec;

Vypíše jenom Led Z, přitom tam žádná značka uprostřed textu není

**Comment by gitpajo** [comment]
Uz rozumim, je to divne, zkoumam to

**Comment by gitpajo** [comment]
Zkus trim jen 'listing)' a uvidime co tam zustane

**Comment by myjavarama4** [comment]
Poslední commit.
