### ISSUE TITLE
Ukladani souboru

### ISSUE THREAD

**Issue by gitpajo** [gitpajo/nfwjob#5]
Ukladani funguje

**Comment by myjavarama4** [comment]
Mně ne

Array
(
    [status] =>  
    [popis] =>    
    [parametry] => Array
        (
            [ ] =>  
        )

)

Tohle se uloží

**Comment by gitpajo** [comment]
dej si echo $obsah at vidis co bude ukladat

**Comment by myjavarama4** [comment]
Nic to nevypisuje

**Comment by gitpajo** [comment]
echo $obsah az za tu promenou $obsah

**Comment by myjavarama4** [comment]
Vypisuje se to, takže problém je v ukládání

Předtím to nevypisoval nic, protože jsem to dal až za to return

**Comment by gitpajo** [comment]
oddelej to unlik, to musime dat jen na zacatek getProdukt a ne pred ulozenim kazdeho produktu

**Comment by myjavarama4** [comment]
Konečně ta svině funguje, teď ještě kam dát to unlink

**Comment by gitpajo** [comment]
Na zacatek getProdukt

**Comment by myjavarama4** [comment]
function getProduct($url) {
    if (file_exists($soubor)) {
        unlink($soubor);
    }
    $obsah_stranky = file_get_html($url);

```
if ($obsah_stranky == false) {
    printr('Nelze načíst stránku');
} else {
    $produkt = array();
    $produkt = getInformation($obsah_stranky, $produkt);
    $produkt = getAvailability($obsah_stranky, $produkt);
    $produkt = getPopis($obsah_stranky, $produkt);
    $produkt = getParametr($obsah_stranky, $produkt);
    $produkt = getImage($obsah_stranky, $produkt);
    $produkt = getInclusion($obsah_stranky, $produkt);
    printr($produkt);
    saveProduct($produkt, 'produkty.txt');
}
```

}

Hlásí undefined variable soubor

**Comment by gitpajo** [comment]
Premyslej chlape

**Comment by myjavarama4** [comment]
$soubor = 'produkty.txt';
    if (file_exists($soubor)) {
        unlink($soubor);
    }

Zase to vypisuje nic

**Comment by gitpajo** [comment]
Nic na obrazovku nebo do souboru?

**Comment by myjavarama4** [comment]
Opět na obrazovku ano, do souboru nic

**Comment by gitpajo** [comment]
Mas pravdu musis to dat jeste pred to foreach s volanim getProduct

**Comment by myjavarama4** [comment]
Konečně ta svině
