### ISSUE TITLE
Stopy a související umělci

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#50]
Nasrat, mám to předělat do pole.

Udělej to ty, já na to nemám nervy na tom šitském webu

**Comment by myjavarama4** [comment]
související umělci už fungují

**Comment by myjavarama4** [comment]
jak si říkal tu funkci?

**Comment by gitpajo** [comment]
$pole = explode("<br>', $prom);

Ty promene si dopln

**Comment by myjavarama4** [comment]
Už to mám, ale vypisuje to nějak divně, poslední commit

[stopy] => Array
        (
            [0] => 1. Immigrant Song 
2. Friends 
3. Celebration Day 
4. Since I've Been Loving You 
5. Out On The Tiles 
6. Gallows Pole
7. Tangerine
8. That's The Way
9. Bron Y Aur Stomp
10. Hats Off To (Roy) Harper
            [1] => 1. Immigrant Song 
2. Friends 
3. Celebration Day 
4. Since I've Been Loving You 
5. Out On The Tiles 
6. Gallows Pole
7. Tangerine
8. That's The Way
9. Bron Y Aur Stomp
10. Hats Off To (Roy) Harper
            [2] => 1. Immigrant Song 
2. Friends 
3. Celebration Day 
4. Since I've Been Loving You 
5. Out On The Tiles 
6. Gallows Pole
7. Tangerine
8. That's The Way
9. Bron Y Aur Stomp
10. Hats Off To (Roy) Harper
        )

**Comment by myjavarama4** [comment]
poslední comit

**Comment by myjavarama4** [comment]
pořád to nefunguje, Call to a member function find() on string problém je v tom volání, když smažu plaintext, tak se to zobrazí s fontem a stejně se to nenaplní do pole

LEZE MNĚ TO NA NERVY - PEKLO TOMU, KDO PSAL TEN WEB

**Comment by gitpajo** [comment]
Uklada se tam i ten tag FONT, dej si source tveho programu v prohlizeci
