### ISSUE TITLE
Uložení ProductInfoEil

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#52]
Produkty se vypisují, ale neukládají do souboru

**Comment by gitpajo** [comment]
Mas stejnou promenou v tom foreach

$url_produkty as $url_produkty

**Comment by myjavarama4** [comment]
Ukládání pořád nefunguje

Poslední commit

**Comment by gitpajo** [comment]
Me se to uklada pekne

**Comment by myjavarama4** [comment]
Tak to jsi v pohodě, mně se to prostě nechce ukládat

**Comment by myjavarama4** [comment]
Nějaká kočka mi mazala soubor
