### ISSUE TITLE
Img InfoEil

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#54]
[img] => Array
        (
            [0] => http://eil.com/images/main/Elvis-Presley-Close-Up-587279.jpg
            [1] => http://eil.com
        )

U produktů, které nemají 2 obrázky, se přesto vypisují dva, druhý obráku je adresa stránky.

**Comment by gitpajo** [comment]
Vzdyt to pisu #53 
musis to osetrit
if ($img)
:horse:

**Comment by myjavarama4** [comment]
už zase, kam mám tu podmínku napsat?

**Comment by gitpajo** [comment]
Tam kde ten img nactes
Jedna podminka jestli nasel obrazek a druha uvnitr toho cyklu jestli je img->src

**Comment by gitpajo** [comment]
Jeste tam dej podminku, kdyz neni vubec obrazek
if ($img) 
hned na druhy radek te funkce

**Comment by myjavarama4** [comment]
zase kam?
