### ISSUE TITLE
class ProductInfo

### ISSUE THREAD

**Issue by myjavarama4** [gitpajo/nfwjob#6]
$produkt = getInformation($obsah_stranky, $produkt);
$produkt = getAvailability($obsah_stranky, $produkt);
$produkt = getPopis($obsah_stranky, $produkt);
$produkt = getParametr($obsah_stranky, $produkt);
$produkt = getImage($obsah_stranky, $produkt);
$produkt = getInclusion($obsah_stranky, $produkt);

U všech funkcí to hlásí

Call to undefined function getInformation()

**Comment by gitpajo** [comment]
$this->getInformation() u PHP je to this povinne

**Comment by myjavarama4** [comment]
A co je zase tohle?

Using $this when not in object context

$produkt = $this->getInformation($obsah_stranky, $produkt);
$produkt = $this->getAvailability($obsah_stranky, $produkt);
$produkt = $this->getPopis($obsah_stranky, $produkt);
$produkt = $this->getParametr($obsah_stranky, $produkt);
$produkt = $this->getImage($obsah_stranky, $produkt);
$produkt = $this->getInclusion($obsah_stranky, $produkt);

**Comment by gitpajo** [comment]
Sorry, je to static self::getInformation()

**Comment by myjavarama4** [comment]
U všech funkcí to hlásí

PHP Strict standards: Non-static method ProductInfo::getInformation() should not be called statically

$produkt = self::getInformation($obsah_stranky, $produkt);
$produkt = self::getAvailability($obsah_stranky, $produkt);
$produkt = self::getPopis($obsah_stranky, $produkt);
$produkt = self::getParametr($obsah_stranky, $produkt);
$produkt = self::getImage($obsah_stranky, $produkt);
$produkt = self::getInclusion($obsah_stranky, $produkt);

A navíc ještě že Call to undefined function saveProduct()

**Comment by gitpajo** [comment]
musi mit vsechny funkce static 
static function getInformation

self::saveProduct

**Comment by myjavarama4** [comment]
Sláva Chucku Norrisovi, konečně to funguje
