### ISSUE TITLE
Adresa serveru na jednom miste

### ISSUE THREAD

**Issue by gitpajo** [gitpajo/nfwjob#8]
self::SERVER_URL - uvnitr class
ProductInfo::SERVER_URL mimo class

**Comment by myjavarama4** [comment]
NECHÁPU

UDĚLEJ COMIT

**Comment by gitpajo** [comment]
Hotovo

**Comment by myjavarama4** [comment]
Undefined class constant 'SERVER_URL'

 ProductInfo::getProduct(ProductInfo::SERVER_URL . '?cls=stoitem&stiid=' . $url_produkty, $soubor);

**Comment by myjavarama4** [comment]
Pořád to nefunguje

**Comment by gitpajo** [comment]
Chybova zprava?

**Comment by myjavarama4** [comment]
Pořád stejná

**Comment by gitpajo** [comment]
Zadnou chybu nevidim, je to nejake divne !?

**Comment by myjavarama4** [comment]
Undefined class constant 'SERVER_URL'

ProductInfo::getProduct(ProductInfo::SERVER_URL . '?cls=stoitem&stiid=' . $url_produkty, $soubor);

**Comment by gitpajo** [comment]
Myslel jsem chybu v programu

**Comment by myjavarama4** [comment]
Nechápu, v jakém programu, NetBeans nic nehlásí

**Comment by gitpajo** [comment]
Chyba v default.php nebo ProductInfo.php
